### ISSUE TITLE
[TYPO] Incorrect Age

### ISSUE THREAD

**Issue by r2dev2** [KentoNishi/kentonishi.github.io#1]
In the `About` section, it says that you are 17 years old as shown in the picture below.

![kento is 17 on the website](https://user-images.githubusercontent.com/50760816/155578655-c8c16dac-6ed3-4a01-9c83-091d40091934.png)

As your birthdate is 24/2/2004, you are actually 18 years old. I am shocked no one noticed the incorrect age sooner.
Happy Birthday Kento!

**Comment by r2dev2** [comment]
Need to ping @KentoNishi

**Comment by anish-lakkapragada** [comment]
based issue

**Comment by KentoNishi** [comment]
lmfao

**Comment by justjustv** [comment]
so true bestie 💅
